# Generated by Django 5.0.2 on 2024-02-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="url",
            new_name="group_url",
        ),
        migrations.AddField(
            model_name="post",
            name="img_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
