# Generated by Django 5.0.2 on 2024-03-03 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag_product_comment_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 17, 16, 13, 8, 668959)
            ),
        ),
    ]
